export const COUNTRIES_ES = [
  { name: 'Afganistán', iso: 'AF' },
  { name: 'Albania', iso: 'AL' },
  { name: 'Alemania', iso: 'DE' },
  { name: 'Andorra', iso: 'AD' },
  { name: 'Angola', iso: 'AO' },
  { name: 'Anguila', iso: 'AI' },
  { name: 'Antigua y Barbuda', iso: 'AG' },
  { name: 'Arabia Saudita', iso: 'SA' },
  { name: 'Argelia', iso: 'DZ' },
  { name: 'Argentina', iso: 'AR' },
  { name: 'Armenia', iso: 'AM' },
  { name: 'Aruba', iso: 'AW' },
  { name: 'Australia', iso: 'AU' },
  { name: 'Austria', iso: 'AT' },
  { name: 'Azerbaiyán', iso: 'AZ' },
  { name: 'Bahamas', iso: 'BS' },
  { name: 'Bangladés', iso: 'BD' },
  { name: 'Barbados', iso: 'BB' },
  { name: 'Baréin', iso: 'BH' },
  { name: 'Bélgica', iso: 'BE' },
  { name: 'Belice', iso: 'BZ' },
  { name: 'Benín', iso: 'BJ' },
  { name: 'Bermudas', iso: 'BM' },
  { name: 'Bielorrusia', iso: 'BY' },
  { name: 'Birmania', iso: 'MM' },
  { name: 'Bolivia', iso: 'BO' },
  { name: 'Bosnia y Herzegovina', iso: 'BA' },
  { name: 'Botsuana', iso: 'BW' },
  { name: 'Brasil', iso: 'BR' },
  { name: 'Brunéi', iso: 'BN' },
  { name: 'Bulgaria', iso: 'BG' },
  { name: 'Burkina Faso', iso: 'BF' },
  { name: 'Burundi', iso: 'BI' },
  { name: 'Bután', iso: 'BT' },
  { name: 'Cabo Verde', iso: 'CV' },
  { name: 'Camboya', iso: 'KH' },
  { name: 'Camerún', iso: 'CM' },
  { name: 'Canadá', iso: 'CA' },
  { name: 'Catar', iso: 'QA' },
  { name: 'Cazajstán', iso: 'KZ' },
  { name: 'Chad', iso: 'TD' },
  { name: 'Chile', iso: 'CL' },
  { name: 'China', iso: 'CN' },
  { name: 'Chipre', iso: 'CY' },
  { name: 'Ciudad del Vaticano', iso: 'VA' },
  { name: 'Colombia', iso: 'CO' },
  { name: 'Comoras', iso: 'KM' },
  { name: 'Congo', iso: 'CG' },
  { name: 'Congo Democrático', iso: 'CD' },
  { name: 'Corea del Norte', iso: 'KP' },
  { name: 'Corea del Sur', iso: 'KR' },
  { name: 'Costa de Marfil', iso: 'CI' },
  { name: 'Costa Rica', iso: 'CR' },
  { name: 'Croacia', iso: 'HR' },
  { name: 'Cuba', iso: 'CU' },
  { name: 'Curazao', iso: 'CW' },
  { name: 'Dinamarca', iso: 'DK' },
  { name: 'Djibouti', iso: 'DJ' },
  { name: 'Dominica', iso: 'DM' },
  { name: 'República Dominicana', iso: 'DO' },
  { name: 'Ecuador', iso: 'EC' },
  { name: 'Egipto', iso: 'EG' },
  { name: 'Emiratos Árabes Unidos', iso: 'AE' },
  { name: 'Eslovakia', iso: 'SK' },
  { name: 'Eslovenia', iso: 'SI' },
  { name: 'España', iso: 'ES' },
  { name: 'Estados Unidos', iso: 'US' },
  { name: 'Estonia', iso: 'EE' },
  { name: 'Esuatini', iso: 'SZ' },
  { name: 'Etiopía', iso: 'ET' },
  { name: 'Filipinas', iso: 'PH' },
  { name: 'Finlandia', iso: 'FI' },
  { name: 'Fiyi', iso: 'FJ' },
  { name: 'Francia', iso: 'FR' },
  { name: 'Gabón', iso: 'GA' },
  { name: 'Gambia', iso: 'GM' },
  { name: 'Georgia', iso: 'GE' },
  { name: 'Georgia del Sur y las Islas Sandwich del Sur', iso: 'GS' },
  { name: 'Gibraltar', iso: 'GI' },
  { name: 'Grecia', iso: 'GR' },
  { name: 'Groenlandia', iso: 'GL' },
  { name: 'Guadalupe', iso: 'GP' },
  { name: 'Guam', iso: 'GU' },
  { name: 'Guatemala', iso: 'GT' },
  { name: 'Guayana Francesa', iso: 'GF' },
  { name: 'Guyana', iso: 'GY' },
  { name: 'Guernesí', iso: 'GG' },
  { name: 'Guinea', iso: 'GN' },
  { name: 'Guinea Ecuatorial', iso: 'GQ' },
  { name: 'Guinea-Bisáu', iso: 'GW' },
  { name: 'Haití', iso: 'HT' },
  { name: 'Honduras', iso: 'HN' },
  { name: 'Hong Kong', iso: 'HK' },
  { name: 'Hungría', iso: 'HU' },
  { name: 'Isla Bouvet', iso: 'BV' },
  { name: 'Isla Christmas', iso: 'CX' },
  { name: 'Isla de Man', iso: 'IM' },
  { name: 'Isla Norfolk', iso: 'NF' },
  { name: 'Islandia', iso: 'IS' },
  { name: 'Islas Åland', iso: 'AX' },
  { name: 'Islas Canarias', iso: 'IC' },
  { name: 'Islas Caicos', iso: 'TC' },
  { name: 'Islas Caimán', iso: 'KY' },
  { name: 'Islas Cocos', iso: 'CC' },
  { name: 'Islas Cook', iso: 'CK' },
  { name: 'Islas Feroe', iso: 'FO' },
  { name: 'Islas Heard y McDonald', iso: 'HM' },
  { name: 'Islas Malvinas', iso: 'FK' },
  { name: 'Islas Mariana del Norte', iso: 'MP' },
  { name: 'Islas Marshall', iso: 'MH' },
  { name: 'Islas Pitcairn', iso: 'PN' },
  { name: 'Islas Salomón', iso: 'SB' },
  { name: 'Islas Turcas y Caicos', iso: 'TC' },
  { name: 'Islas Vírgenes Británicas', iso: 'VG' },
  { name: 'Islas Vírgenes de Estados Unidos', iso: 'VI' },
  { name: 'Islas Wallis y Futuna', iso: 'WF' },
  { name: 'Israel', iso: 'IL' },
  { name: 'Italia', iso: 'IT' },
  { name: 'Jamaica', iso: 'JM' },
  { name: 'Japón', iso: 'JP' },
  { name: 'Jersey', iso: 'JE' },
  { name: 'Jordania', iso: 'JO' },
  { name: 'Jemen', iso: 'YE' },
  { name: 'Kazajistán', iso: 'KZ' },
  { name: 'Kenia', iso: 'KE' },
  { name: 'Kirguistán', iso: 'KG' },
  { name: 'Kiribati', iso: 'KI' },
  { name: 'Kosovo', iso: 'XK' },
  { name: 'Kuwait', iso: 'KW' },
  { name: 'Laos', iso: 'LA' },
  { name: 'Lesoto', iso: 'LS' },
  { name: 'Letonia', iso: 'LV' },
  { name: 'Líbano', iso: 'LB' },
  { name: 'Liberia', iso: 'LR' },
  { name: 'Libia', iso: 'LY' },
  { name: 'Liechtenstein', iso: 'LI' },
  { name: 'Lituania', iso: 'LT' },
  { name: 'Luxemburgo', iso: 'LU' },
  { name: 'Madagascar', iso: 'MG' },
  { name: 'Malasia', iso: 'MY' },
  { name: 'Malawi', iso: 'MW' },
  { name: 'Maldivas', iso: 'MV' },
  { name: 'Mali', iso: 'ML' },
  { name: 'Malta', iso: 'MT' },
  { name: 'Marruecos', iso: 'MA' },
  { name: 'Martinica', iso: 'MQ' },
  { name: 'Mauricio', iso: 'MU' },
  { name: 'Mauritania', iso: 'MR' },
  { name: 'Mayotte', iso: 'YT' },
  { name: 'Mónaco', iso: 'MC' },
  { name: 'Mongolia', iso: 'MN' },
  { name: 'Montenegro', iso: 'ME' },
  { name: 'Montserrat', iso: 'MS' },
  { name: 'Mozambique', iso: 'MZ' },
  { name: 'México', iso: 'MX' },
  { name: 'Micronesia', iso: 'FM' },
  { name: 'Moldavia', iso: 'MD' },
  { name: 'Myanmar', iso: 'MM' },
  { name: 'Namibia', iso: 'NA' },
  { name: 'Nauru', iso: 'NR' },
  { name: 'Nepal', iso: 'NP' },
  { name: 'Nicaragua', iso: 'NI' },
  { name: 'Nigeria', iso: 'NG' },
  { name: 'Niue', iso: 'NU' },
  { name: 'Noruega', iso: 'NO' },
  { name: 'Nueva Caledonia', iso: 'NC' },
  { name: 'Nueva Zelanda', iso: 'NZ' },
  { name: 'Omán', iso: 'OM' },
  { name: 'Países Bajos', iso: 'NL' },
  { name: 'Pakistán', iso: 'PK' },
  { name: 'Palaos', iso: 'PW' },
  { name: 'Palestina', iso: 'PS' },
  { name: 'Panamá', iso: 'PA' },
  { name: 'Papúa Nueva Guinea', iso: 'PG' },
  { name: 'Paraguay', iso: 'PY' },
  { name: 'Perú', iso: 'PE' },
  { name: 'Polinesia Francesa', iso: 'PF' },
  { name: 'Polonia', iso: 'PL' },
  { name: 'Portugal', iso: 'PT' },
  { name: 'Puerto Rico', iso: 'PR' },
  { name: 'Reunión', iso: 'RE' },
  { name: 'Reino Unido', iso: 'GB' },
  { name: 'República Centroafricana', iso: 'CF' },
  { name: 'República Checa', iso: 'CZ' },
  { name: 'República de Macedonia', iso: 'MK' },
  { name: 'República Democrática del Congo', iso: 'CD' },
  { name: 'República Sudafricana', iso: 'ZA' },
  { name: 'Ruanda', iso: 'RW' },
  { name: 'Rumania', iso: 'RO' },
  { name: 'Rusia', iso: 'RU' },
  { name: 'Sahara Occidental', iso: 'EH' },
  { name: 'Samoa', iso: 'WS' },
  { name: 'Samoa Americana', iso: 'AS' },
  { name: 'San Bartolomé', iso: 'BL' },
  { name: 'San Cristóbal y Nieves', iso: 'KN' },
  { name: 'San Marino', iso: 'SM' },
  { name: 'San Martín', iso: 'SX' },
  { name: 'San Pedro y Miquelón', iso: 'PM' },
  { name: 'San Vicente y las Granadinas', iso: 'VC' },
  { name: 'Santa Elena', iso: 'SH' },
  { name: 'Santa Lucía', iso: 'LC' },
  { name: 'Santo Tomé y Príncipe', iso: 'ST' },
  { name: 'Senegal', iso: 'SN' },
  { name: 'Serbia', iso: 'RS' },
  { name: 'Seychelles', iso: 'SC' },
  { name: 'Sierra Leona', iso: 'SL' },
  { name: 'Singapur', iso: 'SG' },
  { name: 'Sint Maarten', iso: 'SX' },
  { name: 'Siria', iso: 'SY' },
  { name: 'Somalia', iso: 'SO' },
  { name: 'Sri Lanka', iso: 'LK' },
  { name: 'Sudáfrica', iso: 'ZA' },
  { name: 'Sudán', iso: 'SD' },
  { name: 'Sudán del Sur', iso: 'SS' },
  { name: 'Suecia', iso: 'SE' },
  { name: 'Suiza', iso: 'CH' },
  { name: 'Surinam', iso: 'SR' },
  { name: 'Svalbard y Jan Mayen', iso: 'SJ' },
  { name: 'Tailandia', iso: 'TH' },
  { name: 'Taiwán', iso: 'TW' },
  { name: 'Tanzania', iso: 'TZ' },
  { name: 'Tayikistán', iso: 'TJ' },
  { name: 'Territorio Británico del Océano Índico', iso: 'IO' },
  { name: 'Territorios Australes Franceses', iso: 'TF' },
  { name: 'Timor Oriental', iso: 'TL' },
  { name: 'Togo', iso: 'TG' },
  { name: 'Tokelau', iso: 'TK' },
  { name: 'Tonga', iso: 'TO' },
  { name: 'Trinidad y Tobago', iso: 'TT' },
  { name: 'Túnez', iso: 'TN' },
  { name: 'Turkmenistán', iso: 'TM' },
  { name: 'Turquía', iso: 'TR' },
  { name: 'Tuvalu', iso: 'TV' },
  { name: 'Ucrania', iso: 'UA' },
  { name: 'Uganda', iso: 'UG' },
  { name: 'Uruguay', iso: 'UY' },
  { name: 'Uzbekistán', iso: 'UZ' },
  { name: 'Vanuatu', iso: 'VU' },
  { name: 'Vaticano', iso: 'VA' },
  { name: 'Venezuela', iso: 'VE' },
  { name: 'Vietnam', iso: 'VN' },
  { name: 'Yibuti', iso: 'DJ' },
  { name: 'Zambia', iso: 'ZM' },
  { name: 'Zimbabue', iso: 'ZW' }
];

export const COUNTRIES_EN = [
  { name: 'Afghanistan', iso: 'AF' },
  { name: 'Albania', iso: 'AL' },
  { name: 'Algeria', iso: 'DZ' },
  { name: 'Andorra', iso: 'AD' },
  { name: 'Angola', iso: 'AO' },
  { name: 'Anguilla', iso: 'AI' },
  { name: 'Antigua and Barbuda', iso: 'AG' },
  { name: 'Argentina', iso: 'AR' },
  { name: 'Armenia', iso: 'AM' },
  { name: 'Aruba', iso: 'AW' },
  { name: 'Australia', iso: 'AU' },
  { name: 'Austria', iso: 'AT' },
  { name: 'Azerbaijan', iso: 'AZ' },
  { name: 'Bahamas', iso: 'BS' },
  { name: 'Bahrain', iso: 'BH' },
  { name: 'Bangladesh', iso: 'BD' },
  { name: 'Barbados', iso: 'BB' },
  { name: 'Belarus', iso: 'BY' },
  { name: 'Belgium', iso: 'BE' },
  { name: 'Belize', iso: 'BZ' },
  { name: 'Benin', iso: 'BJ' },
  { name: 'Bermuda', iso: 'BM' },
  { name: 'Bhutan', iso: 'BT' },
  { name: 'Bolivia', iso: 'BO' },
  { name: 'Bosnia and Herzegovina', iso: 'BA' },
  { name: 'Botswana', iso: 'BW' },
  { name: 'Bouvet Island', iso: 'BV' },
  { name: 'Brazil', iso: 'BR' },
  { name: 'British Indian Ocean Territory', iso: 'IO' },
  { name: 'Brunei', iso: 'BN' },
  { name: 'Bulgaria', iso: 'BG' },
  { name: 'Burkina Faso', iso: 'BF' },
  { name: 'Burundi', iso: 'BI' },
  { name: 'Cambodia', iso: 'KH' },
  { name: 'Cameroon', iso: 'CM' },
  { name: 'Canada', iso: 'CA' },
  { name: 'Cape Verde', iso: 'CV' },
  { name: 'Cayman Islands', iso: 'KY' },
  { name: 'Central African Republic', iso: 'CF' },
  { name: 'Chad', iso: 'TD' },
  { name: 'Chile', iso: 'CL' },
  { name: 'China', iso: 'CN' },
  { name: 'Christmas Island', iso: 'CX' },
  { name: 'Cocos (Keeling) Islands', iso: 'CC' },
  { name: 'Colombia', iso: 'CO' },
  { name: 'Comoros', iso: 'KM' },
  { name: 'Congo', iso: 'CG' },
  { name: 'Cook Islands', iso: 'CK' },
  { name: 'Costa Rica', iso: 'CR' },
  { name: 'Croatia', iso: 'HR' },
  { name: 'Cuba', iso: 'CU' },
  { name: 'Cyprus', iso: 'CY' },
  { name: 'Czech Republic', iso: 'CZ' },
  { name: 'Côte d\'Ivoire', iso: 'CI' },
  { name: 'Curaçao', iso: 'CW' },
  { name: 'Denmark', iso: 'DK' },
  { name: 'Djibouti', iso: 'DJ' },
  { name: 'Dominica', iso: 'DM' },
  { name: 'Dominican Republic', iso: 'DO' },
  { name: 'Ecuador', iso: 'EC' },
  { name: 'Egypt', iso: 'EG' },
  { name: 'El Salvador', iso: 'SV' },
  { name: 'Equatorial Guinea', iso: 'GQ' },
  { name: 'Eritrea', iso: 'ER' },
  { name: 'Estonia', iso: 'EE' },
  { name: 'Eswatini', iso: 'SZ' },
  { name: 'Ethiopia', iso: 'ET' },
  { name: 'Falkland Islands', iso: 'FK' },
  { name: 'Faroe Islands', iso: 'FO' },
  { name: 'Fiji', iso: 'FJ' },
  { name: 'Finland', iso: 'FI' },
  { name: 'France', iso: 'FR' },
  { name: 'French Guiana', iso: 'GF' },
  { name: 'French Polynesia', iso: 'PF' },
  { name: 'French Southern Territories', iso: 'TF' },
  { name: 'Gabon', iso: 'GA' },
  { name: 'Gambia', iso: 'GM' },
  { name: 'Georgia', iso: 'GE' },
  { name: 'Germany', iso: 'DE' },
  { name: 'Ghana', iso: 'GH' },
  { name: 'Gibraltar', iso: 'GI' },
  { name: 'Greece', iso: 'GR' },
  { name: 'Greenland', iso: 'GL' },
  { name: 'Grenada', iso: 'GD' },
  { name: 'Guadeloupe', iso: 'GP' },
  { name: 'Guam', iso: 'GU' },
  { name: 'Guatemala', iso: 'GT' },
  { name: 'Guernsey', iso: 'GG' },
  { name: 'Guinea', iso: 'GN' },
  { name: 'Guinea-Bissau', iso: 'GW' },
  { name: 'Guyana', iso: 'GY' },
  { name: 'Haiti', iso: 'HT' },
  { name: 'Heard Island and McDonald Islands', iso: 'HM' },
  { name: 'Honduras', iso: 'HN' },
  { name: 'Hong Kong', iso: 'HK' },
  { name: 'Hungary', iso: 'HU' },
  { name: 'Iceland', iso: 'IS' },
  { name: 'India', iso: 'IN' },
  { name: 'Indonesia', iso: 'ID' },
  { name: 'Iran', iso: 'IR' },
  { name: 'Iraq', iso: 'IQ' },
  { name: 'Ireland', iso: 'IE' },
  { name: 'Isle of Man', iso: 'IM' },
  { name: 'Israel', iso: 'IL' },
  { name: 'Italy', iso: 'IT' },
  { name: 'Jamaica', iso: 'JM' },
  { name: 'Japan', iso: 'JP' },
  { name: 'Jersey', iso: 'JE' },
  { name: 'Jordan', iso: 'JO' },
  { name: 'Kazakhstan', iso: 'KZ' },
  { name: 'Kenya', iso: 'KE' },
  { name: 'Kiribati', iso: 'KI' },
  { name: 'Kosovo', iso: 'XK' },
  { name: 'Kuwait', iso: 'KW' },
  { name: 'Kyrgyzstan', iso: 'KG' },
  { name: 'Laos', iso: 'LA' },
  { name: 'Latvia', iso: 'LV' },
  { name: 'Lebanon', iso: 'LB' },
  { name: 'Lesotho', iso: 'LS' },
  { name: 'Liberia', iso: 'LR' },
  { name: 'Libya', iso: 'LY' },
  { name: 'Liechtenstein', iso: 'LI' },
  { name: 'Lithuania', iso: 'LT' },
  { name: 'Luxembourg', iso: 'LU' },
  { name: 'Macao', iso: 'MO' },
  { name: 'Madagascar', iso: 'MG' },
  { name: 'Malawi', iso: 'MW' },
  { name: 'Malaysia', iso: 'MY' },
  { name: 'Maldives', iso: 'MV' },
  { name: 'Mali', iso: 'ML' },
  { name: 'Malta', iso: 'MT' },
  { name: 'Marshall Islands', iso: 'MH' },
  { name: 'Martinique', iso: 'MQ' },
  { name: 'Mauritania', iso: 'MR' },
  { name: 'Mauritius', iso: 'MU' },
  { name: 'Mayotte', iso: 'YT' },
  { name: 'Mexico', iso: 'MX' },
  { name: 'Micronesia', iso: 'FM' },
  { name: 'Moldova', iso: 'MD' },
  { name: 'Monaco', iso: 'MC' },
  { name: 'Mongolia', iso: 'MN' },
  { name: 'Montenegro', iso: 'ME' },
  { name: 'Montserrat', iso: 'MS' },
  { name: 'Morocco', iso: 'MA' },
  { name: 'Mozambique', iso: 'MZ' },
  { name: 'Myanmar', iso: 'MM' },
  { name: 'Namibia', iso: 'NA' },
  { name: 'Nauru', iso: 'NR' },
  { name: 'Nepal', iso: 'NP' },
  { name: 'Netherlands', iso: 'NL' },
  { name: 'New Caledonia', iso: 'NC' },
  { name: 'New Zealand', iso: 'NZ' },
  { name: 'Nicaragua', iso: 'NI' },
  { name: 'Niger', iso: 'NE' },
  { name: 'Nigeria', iso: 'NG' },
  { name: 'Niue', iso: 'NU' },
  { name: 'Norfolk Island', iso: 'NF' },
  { name: 'North Korea', iso: 'KP' },
  { name: 'North Macedonia', iso: 'MK' },
  { name: 'Northern Mariana Islands', iso: 'MP' },
  { name: 'Norway', iso: 'NO' },
  { name: 'Oman', iso: 'OM' },
  { name: 'Pakistan', iso: 'PK' },
  { name: 'Palau', iso: 'PW' },
  { name: 'Palestine', iso: 'PS' },
  { name: 'Panama', iso: 'PA' },
  { name: 'Papua New Guinea', iso: 'PG' },
  { name: 'Paraguay', iso: 'PY' },
  { name: 'Peru', iso: 'PE' },
  { name: 'Philippines', iso: 'PH' },
  { name: 'Pitcairn', iso: 'PN' },
  { name: 'Poland', iso: 'PL' },
  { name: 'Portugal', iso: 'PT' },
  { name: 'Puerto Rico', iso: 'PR' },
  { name: 'Qatar', iso: 'QA' },
  { name: 'Republic of the Congo', iso: 'CD' },
  { name: 'Réunion', iso: 'RE' },
  { name: 'Romania', iso: 'RO' },
  { name: 'Russia', iso: 'RU' },
  { name: 'Rwanda', iso: 'RW' },
  { name: 'Saint Barthélemy', iso: 'BL' },
  { name: 'Saint Helena', iso: 'SH' },
  { name: 'Saint Kitts and Nevis', iso: 'KN' },
  { name: 'Saint Lucia', iso: 'LC' },
  { name: 'Saint Martin', iso: 'SX' },
  { name: 'Saint Pierre and Miquelon', iso: 'PM' },
  { name: 'Saint Vincent and the Grenadines', iso: 'VC' },
  { name: 'Samoa', iso: 'WS' },
  { name: 'San Marino', iso: 'SM' },
  { name: 'São Tomé and Príncipe', iso: 'ST' },
  { name: 'Saudi Arabia', iso: 'SA' },
  { name: 'Senegal', iso: 'SN' },
  { name: 'Serbia', iso: 'RS' },
  { name: 'Seychelles', iso: 'SC' },
  { name: 'Sierra Leone', iso: 'SL' },
  { name: 'Singapore', iso: 'SG' },
  { name: 'Sint Maarten', iso: 'SX' },
  { name: 'Slovakia', iso: 'SK' },
  { name: 'Slovenia', iso: 'SI' },
  { name: 'Solomon Islands', iso: 'SB' },
  { name: 'Somalia', iso: 'SO' },
  { name: 'South Africa', iso: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', iso: 'GS' },
  { name: 'South Korea', iso: 'KR' },
  { name: 'South Sudan', iso: 'SS' },
  { name: 'Spain', iso: 'ES' },
  { name: 'Sri Lanka', iso: 'LK' },
  { name: 'Sudan', iso: 'SD' },
  { name: 'Suriname', iso: 'SR' },
  { name: 'Svalbard and Jan Mayen', iso: 'SJ' },
  { name: 'Sweden', iso: 'SE' },
  { name: 'Switzerland', iso: 'CH' },
  { name: 'Syria', iso: 'SY' },
  { name: 'Taiwan', iso: 'TW' },
  { name: 'Tajikistan', iso: 'TJ' },
  { name: 'Tanzania', iso: 'TZ' },
  { name: 'Thailand', iso: 'TH' },
  { name: 'Timor-Leste', iso: 'TL' },
  { name: 'Togo', iso: 'TG' },
  { name: 'Tokelau', iso: 'TK' },
  { name: 'Tonga', iso: 'TO' },
  { name: 'Trinidad and Tobago', iso: 'TT' },
  { name: 'Tunisia', iso: 'TN' },
  { name: 'Turkey', iso: 'TR' },
  { name: 'Turkmenistan', iso: 'TM' },
  { name: 'Turks and Caicos Islands', iso: 'TC' },
  { name: 'Tuvalu', iso: 'TV' },
  { name: 'Uganda', iso: 'UG' },
  { name: 'Ukraine', iso: 'UA' },
  { name: 'United Arab Emirates', iso: 'AE' },
  { name: 'United Kingdom', iso: 'GB' },
  { name: 'United States', iso: 'US' },
  { name: 'United States Minor Outlying Islands', iso: 'UM' },
  { name: 'Uruguay', iso: 'UY' },
  { name: 'Uzbekistan', iso: 'UZ' },
  { name: 'Vanuatu', iso: 'VU' },
  { name: 'Vatican City', iso: 'VA' },
  { name: 'Venezuela', iso: 'VE' },
  { name: 'Vietnam', iso: 'VN' },
  { name: 'Virgin Islands (British)', iso: 'VG' },
  { name: 'Virgin Islands (U.S.)', iso: 'VI' },
  { name: 'Wallis and Futuna', iso: 'WF' },
  { name: 'Western Sahara', iso: 'EH' },
  { name: 'Yemen', iso: 'YE' },
  { name: 'Zambia', iso: 'ZM' },
  { name: 'Zimbabwe', iso: 'ZW' },
  { name: 'Åland Islands', iso: 'AX' }
];

export const getCountries = (language = 'en') => {
  return language === 'es' ? COUNTRIES_ES : COUNTRIES_EN;
};
